version: "3"

services:
  postgres:
    image: postgres:9.6-alpine
#    volumes:
#      - pg_data:/var/lib/postgresql/data
#      - pg_backups:/pg_backups
    environment:
      POSTGRES_USER: "polyaxon"
      POSTGRES_PASSWORD: "polyaxon"
    networks:
      - polyaxon

  rabbitmq:
    hostname: rabbitmq
    image: rabbitmq:3.6.12-management-alpine
    networks:
      - polyaxon

  redis:
    image: redis:3.0-alpine
    networks:
      - polyaxon

  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    networks:
      - polyaxon
    depends_on:
      - rabbitmq
      - postgres
      - redis
    volumes:
      - .:/polyaxon
    ports:
      - "8000:8000"
      - "8001:8001"
      - "6006:6006"
      - "8888:8888"
      - "8000:80"

    environment:
      DJANGO_SETTINGS_MODULE: polyaxon.settings
      MEMCACHE_LOCATION: "memcache:11211"
      SETTINGS_ENV_DIR: "dev"
      DATABASE_URL: "postgres://polyaxon:polyaxon@postgres:5432/polyaxon"
      POLYAXON_AMQP_URL: "rabbitmq:5672"
      POLYAXON_REDIS_CELERY_RESULT_BACKEND_URL: "redis://redis:6379/0"
      POLYAXON_REDIS_JOB_CONTAINERS_URL: "redis://redis:6379/3"
      POLYAXON_REDIS_TO_STREAM_URL: "redis://redis:6379/4"
      POLYAXON_REDIS_SESSIONS_URL: "redis://redis:6379/5"
      POLYAXON_REDIS_EPHEMERAL_TOKENS_URL: "redis://redis:6379/6"
      POLYAXON_REDIS_TTL_URL: "redis://redis:6379/7"
      POLYAXON_HEARTBEAT_URL: "redis://redis:6379/8"
      POLYAXON_GROUP_CHECKS_URL: "redis://redis:6379/9"
      POLYAXON_RABBITMQ_DEFAULT_USER: admin
      POLYAXON_RABBITMQ_DEFAULT_PASS: mypass

  worker:
    build:
      context: .
      dockerfile: ./DockerfileDev
    volumes:
      - .:/polyaxon
    environment:
      POLYAXON_AMQP_URL: "rabbitmq:5672"
      POLYAXON_REDIS_CELERY_RESULT_BACKEND_URL: "redis://redis:6379/0"
      POLYAXON_REDIS_JOB_CONTAINERS_URL: "redis://redis:6379/3"
      POLYAXON_REDIS_TO_STREAM_URL: "redis://redis:6379/4"
      POLYAXON_REDIS_SESSIONS_URL: "redis://redis:6379/5"
      POLYAXON_REDIS_EPHEMERAL_TOKENS_URL: "redis://redis:6379/6"
      POLYAXON_REDIS_TTL_URL: "redis://redis:6379/7"
      POLYAXON_HEARTBEAT_URL: "redis://redis:6379/8"
      POLYAXON_GROUP_CHECKS_URL: "redis://redis:6379/9"
    networks:
      - polyaxon
    depends_on:
      - rabbitmq

#volumes:
#  pg_data: {}
#  pg_backups: {}

networks:
  polyaxon:
